#!/bin/bash

echo starting
exec 2>&1
set -eu
eval "export HOME=~$( id -un )"
export PATH="$HOME/bin:$PATH"

cd "$( git rev-parse --show-toplevel )"

ping -c 1 -n -i 2 -t 300 8.8.4.4

cd dropbox-hacking-photo-manager-next
exec pnpm run dev
