import "./globals.css";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import ProvideContexts from "./provideContexts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

import "@fortawesome/fontawesome-svg-core/styles.css";

import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;

// Import icons individually to reduce bundle size
import { library } from "@fortawesome/fontawesome-svg-core";
import { faTwitter } from "@fortawesome/free-brands-svg-icons";
import { faCoffee } from "@fortawesome/free-solid-svg-icons";
import { Suspense } from "react";
library.add(faCoffee, faTwitter);

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const windowExists = "window" in globalThis;
  // const leafletExists = "leaflet" in globalThis;
  // console.log({ windowExists, leafletExists });

  return (
    <html lang="en">
      <head>
        {/* <script
          src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"
          integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo="
          crossOrigin=""
          async
        ></script> */}
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Suspense
          fallback={
            <div
              style={{
                position: "absolute",
                display: "block",
                top: 0,
                left: 0,
                width: "100%",
                height: "100%",
                margin: "auto",
                fontSize: "80vh",
                textAlign: "center",
                opacity: 0.4,
              }}
            >
              🤔
            </div>
          }
        >
          <ProvideContexts>{children}</ProvideContexts>
        </Suspense>
      </body>
    </html>
  );
}
